version: '3'
services:
  postgresql:
    image: postgres:9.6
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
volumes:
  postgres-data:
    external: false

